In [1]:
import array
k = array.array('f',[11,22,33,44.5])
print(k)
print(type(k))
print(k[0])

array('f', [11.0, 22.0, 33.0, 44.5])
<class 'array.array'>
11.0


In [2]:
import numpy as np

In [4]:
k = [11, 22.2, 'python']
k1 = np.array(k)
print(k1)
print("Data type of k1: ", type(k1))
print("Values are: ", k1)
print("Data type of elements: ", k1.dtype)

['11' '22.2' 'python']
Data type of k1:  <class 'numpy.ndarray'>
Values are:  ['11' '22.2' 'python']
Data type of elements:  <U32


In [10]:
k = np.arange(12)
print("Values: ", k)
print("Data type of k: ", type(k))
print("Data type of each element: ", k.dtype)
print("datatype of any: ", type(k[1]))
print("Dimension of k: ", k.ndim)
print("Shape of k: ", k.shape)
print("No.of elements: ", len(k))

Values:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Data type of k:  <class 'numpy.ndarray'>
Data type of each element:  int32
datatype of any:  <class 'numpy.int32'>
Dimension of k:  1
Shape of k:  (12,)
No.of elements:  12


In [11]:
k1 = k.reshape(3,4)
print(k1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
print("Dimension of k1: ", k1.ndim)
print("Shape of k1: ", k1.shape)
print("No.of rows: ", len(k1))
print("No.of rows: ", k1.shape[0])
print("No.of columns: ", k1.shape[1])

Dimension of k1:  2
Shape of k1:  (3, 4)
No.of rows:  3
No.of rows:  3
No.of columns:  4


In [14]:
m = np.arange(2, 10)
print(m)

[2 3 4 5 6 7 8 9]


In [15]:
m1 = np.arange(2, 20, 3)
print(m1)

[ 2  5  8 11 14 17]


In [16]:
m2 = np.arange(1, 2, .3)
print(m2)

[1.  1.3 1.6 1.9]


In [17]:
m2 = np.arange(1, 2, .01)
print(m2)

[1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11 1.12 1.13
 1.14 1.15 1.16 1.17 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25 1.26 1.27
 1.28 1.29 1.3  1.31 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39 1.4  1.41
 1.42 1.43 1.44 1.45 1.46 1.47 1.48 1.49 1.5  1.51 1.52 1.53 1.54 1.55
 1.56 1.57 1.58 1.59 1.6  1.61 1.62 1.63 1.64 1.65 1.66 1.67 1.68 1.69
 1.7  1.71 1.72 1.73 1.74 1.75 1.76 1.77 1.78 1.79 1.8  1.81 1.82 1.83
 1.84 1.85 1.86 1.87 1.88 1.89 1.9  1.91 1.92 1.93 1.94 1.95 1.96 1.97
 1.98 1.99]


In [18]:
k = np.linspace(1,2,10)
print(k)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [19]:
k1 = np.linspace(1,2,10000)
print(k1)

[1.         1.00010001 1.00020002 ... 1.99979998 1.99989999 2.        ]


In [20]:
k2 = k1.reshape(100, 100)
print(k2)

[[1.         1.00010001 1.00020002 ... 1.00970097 1.00980098 1.00990099]
 [1.010001   1.01010101 1.01020102 ... 1.01970197 1.01980198 1.01990199]
 [1.020002   1.02010201 1.02020202 ... 1.02970297 1.02980298 1.02990299]
 ...
 [1.97009701 1.97019702 1.97029703 ... 1.97979798 1.97989799 1.979998  ]
 [1.98009801 1.98019802 1.98029803 ... 1.98979898 1.98989899 1.989999  ]
 [1.99009901 1.99019902 1.99029903 ... 1.99979998 1.99989999 2.        ]]


In [21]:
k = [11,22]
k1 = np.array(k)
print(k1)
print("Dimension of k1: ", k1.ndim)

[11 22]
Dimension of k1:  1


In [22]:
m = [[11,22], [33,44]]
m1 = np.array(m)
print(m1)
print("Dimension of m1: ", m1.ndim)

[[11 22]
 [33 44]]
Dimension of m1:  2


In [23]:
n = np.arange(12).reshape(3,4,1,1)
print(n)

[[[[ 0]]

  [[ 1]]

  [[ 2]]

  [[ 3]]]


 [[[ 4]]

  [[ 5]]

  [[ 6]]

  [[ 7]]]


 [[[ 8]]

  [[ 9]]

  [[10]]

  [[11]]]]


In [24]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [25]:
k = a + 2
print(k)

[[3 4]
 [5 6]]


In [26]:
k = a > 2
print(k)

[[False False]
 [ True  True]]


In [27]:
a += 3
print(a)

[[4 5]
 [6 7]]


In [28]:
b = np.array([[5,6],[7,8]])
print(b)

[[5 6]
 [7 8]]


In [29]:
c = a + b
print(c)

[[ 9 11]
 [13 15]]


In [30]:
d = a.dot(b)
print(d)

[[55 64]
 [79 92]]


In [32]:
k = np.zeros((3,4))
print(k)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
k = np.ones((3,4))
print(k)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [34]:
a=np.array([[1,2],[3,4]])
print(a)
print("###############")
print("Sum of all:",a.sum())
print("###############")
print("column wise sum:",a.sum(axis=0))
print("###############")
print("row wise sum:",a.sum(axis=1))
print("###############")
print(sum(a))
print("##################")
b=[[1,2],[3,4]]
k=np.array(b,dtype=complex)
print(k)
print("######################")
print(a)
print("Max element:",a.max())
print("column wise Max element:",a.max(axis=0))
print("row wise Max element:",a.max(axis=1))

[[1 2]
 [3 4]]
###############
Sum of all: 10
###############
column wise sum: [4 6]
###############
row wise sum: [3 7]
###############
[4 6]
##################
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
######################
[[1 2]
 [3 4]]
Max element: 4
column wise Max element: [3 4]
row wise Max element: [2 4]
